
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: get gnuplot
        run: |
           sudo apt update
           sudo apt-get install gnuplot

      - name: render
        run: |
          make clean
          make -j all-files
          mv output /tmp

      - name: merge into gh-pages
        run: |
          git config --global user.email "tb2-ci@timb.net"
          git config --global user.name "tb2 Github CI User"
          git fetch origin gh-pages
          git checkout gh-pages
          rm -rf output
          mv /tmp/output .
          git add output/burndown*
          git commit -am "ci built graphs $(date +%Y%m%dT%H%M)"

      - name: push
        run: |
          git push origin HEAD
